config/routes.rb
Kaiwadeck::Application.routes.draw do
  devise_for :users
  
  authenticated :user do
   root to: 'users#dashboard', as: :authenticated_root
  end

  root :to => 'visitors#home'
  resources :decks

  get '/dashboard', to: 'users#dashboard', as: 'dashboard'
  get '/ktc', to: 'visitors#ktc', as: 'ktc'
end

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :deck
end

app/models/deck.rb
class Deck < ActiveRecord::Base
	before_save :fix_card_array
	serialize :cards
	belongs_to :user

	def fix_card_array
	  self[:cards] = self[:cards].split("\r\n")
	  self[:cards].reject! { |c| c.empty? }
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	      :recoverable, :rememberable, :trackable, :validatable
	has_many :decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

	def index
	end

	def show
		@cards = Deck.find(params[:id]).cards.shuffle
	end

	def new
		@deck = Deck.new
	end

	def create
		@deck = Deck.new(deck_params)		
		if @deck.save
      		flash[:notice] = "New Deck Created!"
      		redirect_to decks_path
    	else
      		render 'new'
    	end
	end

	def edit
		@deck = Deck.find(params[:id])
		@deck.cards = @deck.cards.join("\r\n")
	end

	def update
		@deck = Deck.find(params[:id])
		if @deck.update_attributes(deck_params)
      		flash[:notice] = "Deck Updated!"
      		redirect_to decks_path
    	else
      		render 'edit'
    	end
	end

	def delete
	end

	private 
		def deck_params
			params.require(:deck).permit(:name, :cards)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def dashboard
		@user = current_user
		#@recent_decks = @user.decks.where(created_at: )
	end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

	def home
		@decks = Deck.all.where(user_id: 0)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/decks/_deck_form.html.haml
.col-md-6
  = simple_form_for @deck do |f|
    = f.input :name, label: 'Deck Name', :input_html=>{:class=> 'form-control input-lg'}
    <br>
    #card_input
      = f.input :cards, as: :text, label: 'Enter Card Content Here (One Question/Prompt Per Line)', :input_html => {:rows => 10, :style=> 'width: 40em'}
    <br>
    = f.button :submit, class: 'btn btn-primary btn-lg push-bottom'

app/views/decks/edit.html.haml
%section.page-top
  .container
    .row
      .col-md-12
        %h2 Edit the #{@deck.name} deck
.container
  = render "deck_form"

app/views/decks/index.html.haml
%section.page-top
  .container
    .row
      .col-md-12
        %h2 Create a New Deck
.container
  %h3 All Decks 
  %p Try a sample deck
  - Deck.all.each do |deck|
    .deck_name
      = link_to deck.name, deck_path(deck)
      = link_to "(Edit)", edit_deck_path(deck)
    %br
  = link_to "New Deck", new_deck_path 

app/views/decks/new.html.haml
%section.page-top
  .container
    .row
      .col-md-12
        %h2 Create a New Deck
.container
  = render "deck_form"

app/views/decks/show.html.haml
:javascript
	window.cardArray = #{raw @cards.to_json};

%h1
	#card
		= @cards.first
#arrows
	%a{:href =>"#", :id => "previousCard"}
		%i.fa.fa-arrow-circle-left
	%a{:href =>"#", :id => "nextCard"}
		%i.fa.fa-arrow-circle-right

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.container
  %h1.logo
    .alternative-font
      = link_to 'KaiwaDeck', root_path
  %button.btn.btn-responsive-nav.btn-inverse{"data-target" => ".nav-main-collapse", "data-toggle" => "collapse"}
    %i.fa.fa-bars
.navbar-collapse.nav-main-collapse.collapse
  .container
    %nav.nav-main.mega-menu
      %ul#mainMenu.nav.nav-pills.nav-main
        - if user_signed_in?
          = render 'layouts/navigation_links'
        - else
          %li
            = link_to 'Home', root_path
          %li
            = link_to 'Sign Up', new_user_registration_path
          %li
            = link_to 'Sign In', new_user_session_path

app/views/layouts/_navigation_links.html.haml
/ add navigation links to this file 
%ul.nav.navbar-nav.nav-pills.navbar-right
	%li
		= link_to "Your Home", dashboard_path
	%li
		= link_to "Settings", edit_user_registration_path(current_user)
	%li
		= link_to 'Logout', destroy_user_session_path, :method=>'delete'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light", rel: "stylesheet", type: "text/css"}
    %title= content_for?(:title) ? yield(:title) : 'Kaiwa Deck'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Kaiwa Deck'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header#header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
  = javascript_include_tag "application", media: "all", "data-turbolinks-track" => true

app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About the Website
%p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

app/views/users/dashboard.html.haml
%section.page-top
  .container
    .row
      .col-md-12
        %h2 Teacher Dashboard
.container
  #dashboard
    .what-to-do
      %p Here's what you need to prepare a conversation deck:
      %ol
        %li
          Create a #{link_to "new word deck", new_deck_path} or #{link_to "use one of our decks", decks_path}.
        %li
          Take note of the name of your new deck.
        %li
          Have your students go to <strong>kaiwadeck.herokuapp.com/ktc</strong> and choose the deck you just made.
      %strong That's it!
  #buttons
    = link_to "Create a New Deck", new_deck_path, :class => 'btn btn-success btn-xlg'
    = link_to "Use one of our decks", decks_path, :class => 'btn btn-primary btn-xlg'
  %hr
  .row
    .col-md-4
      %h2 Your Decks
      - if @user.decks.count != 0
        %p Open a deck to test the cards inside.
        - @user.decks.each do |deck|
          = link_to "#{deck.name}", deck_path(deck)
          (
          = link_to "Edit", edit_deck_path(deck)
          )
      - else
        %p You haven't made any decks yet.  
-# .col-md-7
-# 	%h2 Recently Used Decks
-# 	- @user.decks.each do |deck|
-# 		= link_to "#{deck.name}", deck_path(deck)
-# 		(
-# 		= link_to "Edit", edit_deck_path(deck)
-# 		)

app/views/visitors/home.html.haml
%section.page-top
  .container
    .row
      .col-md-12
        %h2 Online Conversation Cards
.container
  %h2.word-rotator-title
    Making language teaching
    .word-rotate
      .word-rotate-items
        %span enjoyable.
        %span effortless.
        %span effective.
  .row
    .col-md-10
      %p.lead
        Kaiwa Deck lets teachers create create custom conversation or discussion cards in minutes.        
        %br
        You can try it
        %strong for free
        right now.
  -# TODO enter pics for example
  .row
    = link_to "Try Free Now!", new_user_registration_path, :class => 'btn btn-success btn-xlg btn-block'
    %small *No Hassle. No Downloads.
  %hr.tall
  .row
    .col-md-12
      .row
        .col-md-4
          .feature-box.secundary
            .feature-box-icon
              %i.fa.fa-clock-o
            .feature-box-info
              %h4.shorter Save Time!
              %p.tall You can create entire conversation card decks for an entire classroom on your normal computer in mere minutes. Writing cards by hand takes hours -- hours that you could better spend doing what you do best: teaching. Leave the busywork to the computer.
        .col-md-4
          .feature-box.secundary
            .feature-box-icon
              %i.fa.fa-dollar
            .feature-box-info
              %h4.shorter Save Money!
              %p.tall Don't spend $10-$15 on buying single card decks from traditional publishers -- Kaiwa Deck can make an infinite number of activities! If you plan on using conversation decks three times or more in your teaching career it's much cheaper to use Kaiwa Deck!
        .col-md-4
          .feature-box.secundary
            .feature-box-icon
              %i.fa.fa-file-text-o
            .feature-box-info
              %h4.shorter Save Paper!
              %p.tall Students can use their own iPhones and other smartphones, tablets, or computers to use Kaiwa Deck.
      %hr.tall/
      .row
        .col-md-4
          .feature-box.secundary
            .feature-box-icon
              %i.fa.fa-group
            .feature-box-info
              %h4.shorter Tailor your activities!
              %p.tall If you buy card decks from publishers, you're limited to what they decide is best for you.  If you make custom decks yourself, you will always be able to match them directly to your lesson plan and students.
        .col-md-4
          .feature-box.secundary
            .feature-box-icon
              %i.fa.fa-lightbulb-o
            .feature-box-info
              %h4.shorter Keep your students interested in learning!
              %p.tall If you can think of it, you can put it into a Kaiwa Deck. Use it to prompt discussions, debates, and more.
        .col-md-4
          .feature-box.secundary
            .feature-box-icon
              %i.fa.fa-thumbs-up
            .feature-box-info
              %h4.shorter Buy with confidence.
              %p.tall In addition to a free trial so you can see if KaiwaDeck is right for you, we offer an unconditional 30 day money-back guarantee. If you're not satisfied with our software, we don't deserve your money.
%footer#footer.short
  .container
    .row
      .col-md-8
        %h4 About Kaiwa Deck
        %p
          Kaiwa Deck is made by teacher for teachers. Making life easier and the classroom more fun by letting teachers create custom conversation or discussion cards in mere minutes.
        %hr.light
  .footer-copyright
    .container
      .row
        .col-md-11
          %p © Copyright 2014. All Rights Reserved.

app/views/visitors/ktc.html.haml
%h2 Click on the deck you want to use:
%ul
	- Deck.all.each do |deck|
		.deck_name
			%li
				= link_to deck.name, deck_path(deck)